dist: xenial

language: python

services:
  - postgresql

before_install:
  - printf "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${NPM_TOKEN}\n" >> .npmrc

before_script:
  - psql -c "CREATE DATABASE ductilis;" -U postgres
  - psql -c "CREATE USER ductilis WITH PASSWORD 'ductilis';" -U postgres
  - psql -c "ALTER USER ductilis CREATEDB;" -U postgres
  - psql -c "ALTER ROLE ductilis SET client_encoding TO 'utf8';" -U postgres
  - psql -c "ALTER ROLE ductilis SET default_transaction_isolation TO 'read committed';" -U postgres
  - psql -c "ALTER ROLE ductilis SET timezone TO 'UTC';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE ductilis TO ductilis;" -U postgres

matrix:
  include:
    - language: python
      python:
        - 3.6.5
      install:
        - pip install -r requirements.txt
      script:
        - python manage.py test

    - language: node_js
      node_js:
        - 11.1
      install:
        - yarn install
      script:
        - yarn test
